---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: productpage
    version: v1
    service: public
  name: productpage-v1-public
  namespace: bookinfo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9080
  selector:
    app: productpage
    version: v1
  type: LoadBalancer
status:
  loadBalancer: {}
